// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bibliotekssystem_notification_service.Data;

#nullable disable

namespace bibliotekssystem_notification_service.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260327143743_AddReviewAndAdminLoanTemplates")]
    partial class AddReviewAndAdminLoanTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("bibliotekssystem_notification_service.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("bibliotekssystem_notification_service.Models.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("NotificationTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyTemplate = "Hej! Ditt lånade material ska lämnas tillbaka senast {DueDate}.",
                            Subject = "Påminnelse: Lån förfaller snart",
                            Type = "LoanDueReminder"
                        },
                        new
                        {
                            Id = 2,
                            BodyTemplate = "Ditt lånade material skulle ha lämnats tillbaka {DueDate}. Vänligen återlämna snarast.",
                            Subject = "Försenad återlämning",
                            Type = "OverdueNotice"
                        },
                        new
                        {
                            Id = 3,
                            BodyTemplate = "Det du reserverade är nu tillgängligt för upphämtning.",
                            Subject = "Din reservation är redo",
                            Type = "ReservationReady"
                        },
                        new
                        {
                            Id = 4,
                            BodyTemplate = "Du har lånat ett objekt. Återlämningsdatum: {DueDate}.",
                            Subject = "Lån bekräftat",
                            Type = "LoanConfirmation"
                        },
                        new
                        {
                            Id = 5,
                            BodyTemplate = "Tack! Din återlämning har registrerats.",
                            Subject = "Återlämning bekräftad",
                            Type = "ReturnConfirmation"
                        },
                        new
                        {
                            Id = 6,
                            BodyTemplate = "En förändring har gjorts i hantera katalog.",
                            Subject = "Ändring i hantera katalog",
                            Type = "AdminCatalogChange"
                        },
                        new
                        {
                            Id = 7,
                            BodyTemplate = "En förändring har gjorts i hantera användare.",
                            Subject = "Ändring i hantera användare",
                            Type = "AdminUserChange"
                        },
                        new
                        {
                            Id = 8,
                            BodyTemplate = "En förändring har gjorts i hantera recensioner.",
                            Subject = "Ändring i hantera recensioner",
                            Type = "AdminReviewChange"
                        },
                        new
                        {
                            Id = 9,
                            BodyTemplate = "En förändring har gjorts i hantera lån.",
                            Subject = "Ändring i hantera lån",
                            Type = "AdminLoanChange"
                        },
                        new
                        {
                            Id = 10,
                            BodyTemplate = "Du har skapat en recension.",
                            Subject = "Skapat en recension",
                            Type = "ReviewConfirmation"
                        },
                        new
                        {
                            Id = 11,
                            BodyTemplate = "Du har tagit bort en recension.",
                            Subject = "Raderat en recension",
                            Type = "ReviewRemove"
                        });
                });

            modelBuilder.Entity("bibliotekssystem_notification_service.Models.Notification", b =>
                {
                    b.HasOne("bibliotekssystem_notification_service.Models.NotificationTemplate", "Template")
                        .WithMany("Notifications")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("bibliotekssystem_notification_service.Models.NotificationTemplate", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
